name: Serverless sheduler

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Call api scheduler
        env:
          API_DOMAIN: ${{ secrets.API_DOMAIN }}
          API_SECRET: ${{ secrets.API_SECRET }}
        if: env.API_DOMAIN && env.API_SECRET
        run: curl "$API_DOMAIN/api/scheduler?secret=$API_SECRET"


